### ISSUE TITLE
Writing IDs

### ISSUE THREAD

**Issue by dw-dot** [hubmapconsortium/hra-rui-locations-processor#2]
@hsjoshi28

- _default_ ids are not generated for "Donor" entity
- there is not an option to determine an id for the "Sample" entity
- issue might extend to "Dataset" entity

See most recent commit [#0729b74](https://github.com/hubmapconsortium/hra-rui-locations-processor/commit/0729b74a2319d5da92b794ea0c2e79426b202387)

**Comment by hsjoshi28** [comment]
Made code changes, added a few more functionalities, reviewed, and pushed in main.
